### ISSUE TITLE
SDK Fails in testnet

### ISSUE THREAD

**Issue by bcodesido** [blocktrail/blocktrail-sdk-nodejs#122]
The wallet is not working when you try to get an address in BTC Testnet.

Im using blocktrail-sdk@3.7.16

When I run this example code, fails:
```
var blocktrail = require('blocktrail-sdk');
undefined
> var client = blocktrail.BlocktrailSDK({ apiKey: "APIKEY", apiSecret: "APISECRET", network: "BTC", TestNet: true})
undefined
> client.address('n33npN2oRNJFFpdoxkrm2CVyZAfRGFxALt', function(err, address) { console.log(address.balance); });
{ state: 'pending' }
> TypeError: Cannot read property 'balance' of null
    at repl:1:99
> client.address("n33npN2oRNJFFpdoxkrm2CVyZAfRGFxALt", function(err, address){ if(err){console.log(err)} console.log(address); });
{ state: 'pending' }
> TypeError: Cannot read property 'address' of null
    at BtccomConverter.convertAddress (/home/user/node_modules/blocktrail-sdk/lib/btccom.convert.js:412:33)
    at /home/user/node_modules/blocktrail-sdk/lib/api_client.js:591:39
    at _fulfilled (/home/user/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/user/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/user/node_modules/q/q.js:749:13)
    at /home/user/node_modules/q/q.js:557:44
    at flush (/home/user/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
null
```

**Comment by akhilesharora** [comment]
Its happening because you missed the testnet flag ` testnet : true ` otherwise the call will fail.

```var blocktrail = require('../../main');

var sdk = blocktrail.BlocktrailSDK({
    apiKey : process.env.BLOCKTRAIL_SDK_APIKEY || "EXAMPLE_BLOCKTRAIL_SDK_NODEJS_APIKEY",
    apiSecret : process.env.BLOCKTRAIL_SDK_APISECRET || "EXAMPLE_BLOCKTRAIL_SDK_NODEJS_APISECRET",
    testnet : true,
    btccom: true
});

sdk
    .address("n33npN2oRNJFFpdoxkrm2CVyZAfRGFxALt")
    .then(function(address) {
        console.log(JSON.stringify(address, null, 4));
    }, function(error) {
        console.log(error);
    });
```

**Comment by bcodesido** [comment]
Using what @akhilesharora says also fails:

I'm now using blocktrail-sdk@3.7.21

```
var sdk = blocktrail.BlocktrailSDK({
    apiKey : "XXXXXXXXXXXXXXXXXXX",
    apiSecret : "XXXXXXXXXXXXXXXXXX",
    testnet : true,
    btccom: true
});

> sdk.address("n33npN2oRNJFFpdoxkrm2CVyZAfRGFxALt").then(function(address) {console.log(JSON.stringify(address, null, 4));}, function(error) {console.log(error);});
{ state: 'pending' }
> { Error
    at Function.Request.handleFailure (/home/user/node_modules/blocktrail-sdk/lib/request.js:222:17)
    at /home/user/node_modules/blocktrail-sdk/lib/request.js:169:31
    at Request.callback (/home/user/node_modules/superagent/lib/node/index.js:728:3)
    at IncomingMessage.parser (/home/user/node_modules/superagent/lib/node/index.js:916:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) statusCode: 504 }
```
