### ISSUE TITLE
NPM install fails on Windows 10 unless using Git bash shell

### ISSUE THREAD

**Issue by coinables** [blocktrail/blocktrail-sdk-nodejs#39]
I've tried installing `npm install blocktrail-sdk` and cloning from github then `npm install`.  Both ways fail. I'm only able to get it to install properly when using the Git bash shell `npm install blocktrail-sdk`. Any ideas why this is?

**Comment by rubensayshi** [comment]
Do you have output of the failing install? afaik it creates a `npm-debug.log` when it fails as well in the directory

**Comment by coinables** [comment]
Sorry for the delay in response. Yes the debug file is a couple thousand lines long though. Here's the part that stood out to me that made me try it through the git shell instead. 

```
1106 verbose request no auth needed
1107 info attempt registry request try #1 at 7:49:22 PM
1108 verbose etag W/"5858ae9a-3481"
1109 verbose lastModified Tue, 20 Dec 2016 04:07:54 GMT
1110 http request GET https://registry.npmjs.org/assert-plus
1111 warn addRemoteGit Error: not found: git
1111 warn addRemoteGit     at F (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:72:28)
1111 warn addRemoteGit     at E (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:75:29)
1111 warn addRemoteGit     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:83:16
1111 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
1111 warn addRemoteGit  git://github.com/blocktrail/bip39.git#sjcl-browser-bip39 resetting remote C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb because of error: { [Error: not found: git] code: 'ENOGIT' }
1112 info resetRemote resetting C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb for git://github.com/blocktrail/bip39.git#sjcl-browser-bip39
1113 silly gentlyRm C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb is being purged
1114 verbose gentlyRm don't care about contents; nuking C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb
1115 warn addRemoteGit Error: not found: git
1115 warn addRemoteGit     at F (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:72:28)
1115 warn addRemoteGit     at E (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:75:29)
1115 warn addRemoteGit     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:83:16
1115 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
1115 warn addRemoteGit  git://github.com/blocktrail/qrcode-js.git#master resetting remote C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9 because of error: { [Error: not found: git] code: 'ENOGIT' }
1116 info resetRemote resetting C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9 for git://github.com/blocktrail/qrcode-js.git#master
1117 silly gentlyRm C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9 is being purged
1118 verbose gentlyRm don't care about contents; nuking C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9
1119 warn addRemoteGit Error: not found: git
1119 warn addRemoteGit     at F (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:72:28)
1119 warn addRemoteGit     at E (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:75:29)
1119 warn addRemoteGit     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\which\which.js:83:16
1119 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
1119 warn addRemoteGit  git://github.com/blocktrail/sjcl.git#minify-library resetting remote C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-sjcl-git-f68b1a52 because of error: { [Error: not found: git] code: 'ENOGIT' }
1120 info resetRemote resetting C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-sjcl-git-f68b1a52 for git://github.com/blocktrail/sjcl.git#minify-library
1121 silly gentlyRm C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-sjcl-git-f68b1a52 is being purged
1122 verbose gentlyRm don't care about contents; nuking C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-sjcl-git-f68b1a52
1123 silly vacuum-fs purging C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb
1124 silly vacuum-fs purging C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9
1125 silly vacuum-fs purging C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-sjcl-git-f68b1a52
1126 silly vacuum-fs quitting because other entries in C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes
1127 silly vacuum-fs quitting because other entries in C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes
1128 silly vacuum-fs quitting because other entries in C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes
1129 error git clone --template=C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/blocktrail/qrcode-js.git C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9: undefined
1129 error git clone --template=C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/blocktrail/qrcode-js.git C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-qrcode-js-git-fa213ba9: undefined
1130 error git clone --template=C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/blocktrail/bip39.git C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb: undefined
1130 error git clone --template=C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/blocktrail/bip39.git C:\Users\Kyle\AppData\Roaming\npm-cache\_git-remotes\git-github-com-blocktrail-bip39-git-91b093fb: undefined
```

**Comment by rubensayshi** [comment]
Hmm it seems you need `git` installed
